### PR TITLE
Updates for 1.0 core libraries

### PR DESCRIPTION
**Pull request by paf31**
cc @hdgarrood 

This depends on `node-buffer` being updated, then `bower.json` needs to be updated accordingly.

### CODE REVIEW

**Comment by jplatte** [comment]
`purescript-node-buffer` has been updated. Can we complete this?

**Comment by hdgarrood** [comment]
Yeah, I know, I updated node-buffer ;) This is on my to do list. I will address it when I get a moment.

**Comment by paf31** [comment]
Updated

**Comment by hdgarrood** [comment]
👍 thanks!

**Pull request merged**
