### PR TITLE
fix example

### PR DESCRIPTION
**Pull request by matthewleon**
Update node dependencies and fix example.

### CODE REVIEW

**Comment by paf31** [comment]
CI is failing because eslint is unhappy about something. Also, I don't think we need `package-lock.json` to be in the repo, could you please remove it?

Seems good otherwise!

**Comment by matthewleon** [comment]
Looks like I forgot to check in the rc file for eslint. It should be there.

I've remove the package lock file. A bit of confusion here, though; isn't it generally considered best practice to include it? Our npm dep tree on these isn't particularly sophisticated, but I would think that it would serve to remove one potential source of (admittedly unlikely) error.

**Comment by matthewleon** [comment]
rebased

**Comment by paf31** [comment]
@hdgarrood Any thoughts on this?

**Comment by hdgarrood** [comment]
:+1:. I haven't had enough contact with recent versions of `npm` to have an opinion on whether `package-lock.json` should be checked in.

**Comment by garyb** [comment]
I don't think it should personally, since `npm` dev dependencies are a convenience for building PS projects, not a requirement - also, for the core libraries at least, they're just secondary tools in the build, the compiler isn't even versioned in there (the core libs always fetch the latest release from GH). It's a little different here as I guess the compiler is mentioned specifically, but yeah, I dunno.

I've been adding it to the `gitignore`s lately, as if we neither have it committed nor have it ignored the pursuit auto-publish-on-release will fail.

**Comment by garyb** [comment]
Oh wait, this one is set up to pull latests GH release too, so it also doesn't have a compiler version in the package.json, so disregard that part.

**Comment by JordanMartinez** [comment]
The example provided by this PR seems good. We would need to fix the merge conflicts, update to `Effect` and remove some of the other changes made here regarding NPM things.

**Comment by JordanMartinez** [comment]
Superceded by #36

**Pull request closed without merging**
