### PR TITLE
Update bower.json to latest purescript-aff

### PR DESCRIPTION
**Pull request by srghma**
because I've got error on `spago publish`
```
❌ Could not solve the package dependencies, errors:
  While solving node-streams each version could not be solved:
- 9.0.0: Conflict in version ranges for aff:
    >=8.0.0 (declared dependency)
    <8.0.0 seen in node-streams@9.0.0
```
**Description of the change**

Clearly and concisely describe the purpose of the pull request. If this PR relates to an existing issue or change proposal, please link to it. Include any other background context that would help reviewers understand the motivation for this PR.

---

**Checklist:**

- [ ] Added the change to the changelog's "Unreleased" section with a reference to this PR (e.g. "- Made a change (#0000)")
- [ ] Linked any existing issues or proposals that this pull request should close
- [ ] Updated or added relevant documentation
- [ ] Added a test for the contribution (if applicable)

### CODE REVIEW

**Comment by jamesdbrock** [comment]
Here is the conflict:

```
Unable to find a suitable version for purescript-parallel, please choose one by typing one of the numbers below:
    1) purescript-parallel#^v6.0.0 which resolved to 6.0.0 and is required by purescript-spec#7.6.1
    2) purescript-parallel#^6.0.0 which resolved to 6.0.0 and is required by purescript-aff#7.1.0
    3) purescript-parallel#^7.0.0 which resolved to 7.0.0 and is required by purescript-aff#8.0.0
```

**Comment by srghma** [comment]
cannot run tests

**Comment by jamesdbrock** [comment]
I asked on the PureScript discord and @f-f says that he thinks it's a good time to delete the `bower.json` and create a `spago.yaml`. https://discord.com/channels/864614189094928394/872649585816911912/1288404057404473356

**Comment by jamesdbrock** [comment]
I made PR #57 , maybe that is the solution.

**Pull request closed without merging**
